// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241015131740_min_init")]
    partial class min_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Fast Food",
                            Description = "İnce hamurun üzerine sıcak baharatlarla harmanlanmış kıyma, domates ve soğan konularak pişirilen geleneksel Türk lezzeti.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Lahmacun",
                            Price = 25.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Dessert",
                            Description = "İnce tel kadayıfın içine peynir konularak pişirilir ve üzerine şerbet dökülür. Türkiye'nin en sevilen tatlılarından biri.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Künefe",
                            Price = 35.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Main Course",
                            Description = "İnce dilimlenmiş dana eti, tava da pişirilir ve pide ekmeği üzerine dökülür. Üzerine yoğurt ve domates sosu dökülür.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "İskender Kebap",
                            Price = 50.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Dessert",
                            Description = "İnce yufkalar arasına fıstık konularak yapılan ve şerbet ile tatlandırılan geleneksel Türk tatlısı.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Baklava",
                            Price = 40.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
