// <auto-generated />
using System;
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241015125612_mig_init")]
    partial class mig_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CraetedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "10OFF",
                            CraetedDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 10.0,
                            MinAmount = 20
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "20OFF",
                            CraetedDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 20.0,
                            MinAmount = 40
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "30OFF",
                            CraetedDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 30.0,
                            MinAmount = 60
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "40OFF",
                            CraetedDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 40.0,
                            MinAmount = 80
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "50OFF",
                            CraetedDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 50.0,
                            MinAmount = 100
                        },
                        new
                        {
                            CouponId = 6,
                            CouponCode = "60OFF",
                            CraetedDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 60.0,
                            MinAmount = 120
                        },
                        new
                        {
                            CouponId = 7,
                            CouponCode = "70OFF",
                            CraetedDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 70.0,
                            MinAmount = 140
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
